### ISSUE TITLE
Introduce !cleanup command

### ISSUE THREAD

**Issue by Maddosaurus** [Maddosaurus/HansBot#4]
It would be nice if Hans could clean behind himself.  
On invoking `!cleanup`, Hans could delete all messages related to moving people or mentions/answers of Hans. This includes the message authors that invoked the bot.

**Comment by hernandeztimothy15** [comment]
Hey, i'm just a random guy searching for good first issues on GitHub and found this. Potential solution #1. Make a dedicated channel for bot commands responses, making it easy to just clear the channel through discord
Potential solution #2: For user invoked messages to be deleted perhaps easiest way to do this is to delete them after a set time? For bot messages there is a function one could write to delete all bot messages. Your bot needs the manage_messages permission to delete others messages. Let me know what you think and if i can submit a pull request for a function you like! :)

**Comment by hernandeztimothy15** [comment]
Didn't mean to link commits like this, kinda new to github so excuse my formatting errors

**Comment by Maddosaurus** [comment]
I was thinking about the bot keeping an internal state of every message it reacted to (as well as the bots' answer).  
The idea of a bot channel is the way to go for most stuff, but we all know that especially in bigger groups, it's hard to enforce conventions. It might be a good idea to introduce a bot channel but not restricting the bot to this channel only, instead implementing the cleanup command nontheless.  

Regarding the formatting errors: No worries :) Two hints: There's an edit function for comments, which saved my butt countless times. Also, GitHub uses their own extended Markdown syntax in these comments, [have a look at it here](https://help.github.com/en/articles/basic-writing-and-formatting-syntax)

**Comment by tobinatore** [comment]
It doesn't seem like Timothy submitted a pull request.    
I'd take the issue if it's still free.

BTW: 

> I was thinking about the bot keeping an internal state of every message it reacted to (as well as the  bots' answer).   
 
It would probably be easier to just load the channel history and delete every message which fits the criteria (starts with either "!" or "Hans", mentions @Hans or was sent by Hans himself).    
Unless there's an unexpected pitfall with that approach?

**Comment by Maddosaurus** [comment]
Yes, a PR would be most welcome :)  

Regarding history behavior, there's multiple things to consider.  
Computational-wise, it most certainly is more expensive to search through all channels, especially if we're talking about a very active Discord server.  
Also, Hans already "knows" the full message it was triggered with, so keeping state of it is kind of "batteries included".  
Last but not least: I'm a bit concerned to let a bot mass-delete all messages from all channels matching specific criteria. Deleting messages cannot be undone, so what's gone is gone. Might be the enterprise dev that's speaking out of me :)

**Comment by tobinatore** [comment]
> Computational-wise, it most certainly is more expensive to search through all channels, especially if we're talking about a very active Discord server.

Looks like I first misunderstood that part. I thought the bot should only clean the channel the command was invoked in. Having it search the whole list of channels on the server would not be ideal.

> I'm a bit concerned to let a bot mass-delete all messages from all channels matching specific criteria. Deleting messages cannot be undone, so what's gone is gone.

That is indeed a valid concern especially for the "!" in the beginning of a message rule.   
What about messages like "Hans! Long time no see!" which are directed at another user? The bot would most certainly react to that message and it would be deleted in your approach as well as in mine.

> Also, Hans already "knows" the full message it was triggered with, so keeping state of it is kind of "batteries included".

Thanks for showing me the (rather obvious) flaws with my approach. I'll look into implementing yours.

**Comment by Maddosaurus** [comment]
> That is indeed a valid concern especially for the "!" in the beginning of a message rule.
What about messages like "Hans! Long time no see!" which are directed at another user? The bot would most certainly react to that message and it would be deleted in your approach as well as in mine.  

Having used Hans for a while on our Discord, it became apparent that most people are interested in deleting the messages revolving around the "!treppe" command, as its output is rather verbose and spammy. Thinking about it, it might even be enough to delete that triggered !treppe, !help and !wochenende.   
The flamethrower GIFs are entertaining enough that people want to keep them ;)

> Thanks for showing me the (rather obvious) flaws with my approach. I'll look into implementing yours.

To be fair: Looking at the code right now, its quite slapped together and would profit from a little bit of refactoring with readability and maintainability in mind. Sorry you have to wade through this mess. This kind of stuff is easy to miss in the current implementation.

**Comment by tobinatore** [comment]
>Having used Hans for a while on our Discord, it became apparent that most people are interested in deleting the messages revolving around the "!treppe" command, as its output is rather verbose and spammy. Thinking about it, it might even be enough to delete messages that triggered !treppe, !help and !wochenende (and their answers).
The flamethrower GIFs are entertaining enough that people want to keep them ;)

I have just finished implementing a working version of the !cleanup command using your approach (with the messages we might want to delete being stored in a list). That allows for a lot of freedom on which messages to keep, as I'd just need to add an exception for messages starting with "*reicht" to keep the flamethrower gifs ;) .

> Sorry you have to wade through this mess.

No problem, the project isn't too large, it's still relatively easy to understand what everything does.      
   
I'll finish up my changes and open the PR.

**Comment by Maddosaurus** [comment]
Thank you for this contribution ❤️
